baseURL: "https://james2a6.github.io/" 
title: Ann Mary James
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
         # url: books/
          #weight: 5 
        #- name: Papers
         # url: papers/
          #weight: 2
        #- name: Courses
         # url: courses/
          #weight: 3
        #- name: Data
         # url: data/
          #weight: 4 
        #- name: Blog
         # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          #weight: 6
        - name: Resume
          url: resume/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2

params:
    description: "I am an applied economist specializing in macroeconomics, econometrics, and data analytics."
    author: Ann Mary James
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    MainSections: ["resume","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ann Mary James
          subtitle: "👋🏼 I am an Applied Economist specializing in Macroeconomics, Econometrics, and Data Analytics. My work explores the complexities of economic systems through advanced **Statistical Modeling, Data-driven Research, and Theoretical Analysis**. I focus on key areas such as **forecasting, labor markets, monetary policy, energy economics, and real estate trends**.
          <br> <br> By leveraging tools like **R, SQL, Tableau, Power BI, MS Excel, Stata, and Python**, I transform data into actionable insights that bridge academic research and practical solutions. My research is driven by a commitment to addressing real-world challenges and contributing to informed policy-making and strategic decision-making. For more information about my work and experience, please refer to my resume.
          
          <br> <br> **Interests**: Economic Theory, Econometrics, Statistical Analysis, Quantitative Analysis, Market Research, Mathematical Economics, Macroeconomics, Game Theory, Time Series Analysis, Panel Data Analysis"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            #- name: Papers
             # url: papers/
            #- name: Courses
             # url: courses/
            #- name: Data
             # url: data/
            #- name: Books
             # url: books/
            #- name: Tags
             # url: tags/
            #- name: Archive
             # url: archive/
            - name: Resume
              url: resume/
            - name: Projects
              url: projects/
            #- name: Blog
             # url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        #- name: CV
        #  url: cv.pdf
        - name: Email
          url: mailto:james2a6@mail.uc.edu
        #- name: Zoom
         # url: https://www.zoom.us/my/igelfeld
        #- name: Location
         # url: location/
        #- name: Office Hours
         # url: officehours/
        #- name: Google Scholar
         # url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: LinkedIn
          url: https://www.linkedin.com/in/ann16
        - name: GitHub
          url: https://github.com/james2a6
        #- name: Substack
         # url: https://pmichaillat.substack.com
        #- name: YouTube
         # url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
         # url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ann Mary James"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2